### ISSUE TITLE
NAPS dataset: distinguishing 'search' from 'test' IO examples

### ISSUE THREAD

**Issue by mtensor** [nearai/program_synthesis#10]
Hello,
The NAPS paper says, "Each full solution is accompanied with 2-10 inputs/outputs each split into two groups. The first group can be used in search or can be included into the problem specification
as part of the model input. The second group can be used for the evaluation at the test time."
However in the NAPS dataset, it seems that there is a single list of IO examples with the key 'tests'. How may I distinguish 'search' examples from 'test' examples?

Thanks.

**Comment by nearmax** [comment]
Added split tests pipe in https://github.com/nearai/program_synthesis/commit/9e64e067ff307294fe0a7aa36ba89314e98180fe

Use it to deterministically split tests upon reading the dataset.
