### ISSUE TITLE
Is seq2tree open-sourced?

### ISSUE THREAD

**Issue by izgzhen** [nearai/program_synthesis#12]
Just curious since I can't find it easily. If not, is there a plan to do so?

Thanks! Feel free to close this issue anytime.

**Comment by ilblackdragon** [comment]
We had a plan, but we pivoted away from this project (to http://nearprotocol.com).
If you are interested, I can just dump out the code for the model without cleaning up.

**Comment by varunjain3** [comment]
@izgzhen Did you get any updates on the following repository/seq2seq model?
